#!/usr/bin/env bash
# Install Pokémon TCG Live with Lutris Flatpak and Proton-GE.
# Usage: ./install.sh [/path/to/PokemonTCGLiveInstaller.msi]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"
source "${SCRIPT_DIR}/lib/deps.sh"
source "${SCRIPT_DIR}/lib/proton.sh"

# Reuse an existing prefix, including installations made with the old launcher.
if [[ -f "$STATE_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$STATE_FILE"
    set_prefix_paths
fi

# Validate the MSI before installing dependencies. Existing games need no MSI.
MSI_PATH="${1:-}"
if [[ ! -f "$GAME_EXE" ]]; then
    step "Locating MSI installer"
    if [[ -z "$MSI_PATH" ]]; then
        if [[ -f "${HOME}/Downloads/PokemonTCGLiveInstaller.msi" ]]; then
            MSI_PATH="${HOME}/Downloads/PokemonTCGLiveInstaller.msi"
        else
            read -rp "Enter full path to PokemonTCGLiveInstaller.msi: " MSI_PATH
        fi
    fi
    MSI_PATH="${MSI_PATH/#\~/$HOME}"
    [[ -f "$MSI_PATH" ]] || die "MSI not found at: ${MSI_PATH}"
    [[ "${MSI_PATH,,}" == *.msi ]] || die "File does not appear to be an MSI: ${MSI_PATH}"
fi

install_deps

step "Installing Lutris (Flatpak)"
if flatpak info --user "$LUTRIS_FLATPAK" &>/dev/null; then
    success "Lutris already installed for this user"
elif flatpak info --system "$LUTRIS_FLATPAK" &>/dev/null; then
    success "Lutris already installed system-wide"
else
    flatpak install --user -y flathub "$LUTRIS_FLATPAK" \
        || die "Failed to install Lutris via Flatpak."
fi

step "Preparing Lutris's UMU runtime"
lutris_helper ensure-umu \
    || die "Could not prepare Lutris's UMU runtime. See the diagnostic above."
# Ask Lutris for the actual runner directory (respects its custom settings).
LUTRIS_TOOLS=$(lutris_helper wine-dir) \
    || die "Could not locate Lutris's Wine runners directory."
[[ "$LUTRIS_TOOLS" == /* ]] || die "Invalid Lutris runners directory: ${LUTRIS_TOOLS}"
install_proton_ge
PROTON_ROOT="${LUTRIS_TOOLS}/${PROTON_VERSION}"

step "Installing game in the Wine prefix"
if [[ -f "$GAME_EXE" ]]; then
    success "Reusing existing game: ${GAME_EXE}"
else
    mkdir -p "$WINE_PREFIX"
    MSI_STAGING="${WINE_PREFIX}/drive_c/ptcgl_install"
    mkdir -p "$MSI_STAGING"
    cp "$MSI_PATH" "${MSI_STAGING}/installer.msi"
    info "Running MSI installer with Lutris's UMU runtime..."
    lutris_helper run --proton-root "$PROTON_ROOT" --prefix "$WINE_PREFIX" \
        msiexec /i 'C:\ptcgl_install\installer.msi' /passive /norestart \
        || warn "msiexec returned non-zero — checking the installed executable."
    [[ -f "$GAME_EXE" ]] \
        || die "Game executable not found: ${GAME_EXE}\nCheck the MSI installation inside ${WINE_PREFIX}/drive_c/."
    rm -rf "$MSI_STAGING"
    success "Game installed: ${GAME_EXE}"
fi

step "Registering game in Lutris"
lutris_helper register --slug "$APP_NAME" --config-id "$LUTRIS_CONFIG_ID" \
    --title "$GAME_TITLE" --version "$PROTON_VERSION" --proton-root "$PROTON_ROOT" \
    --prefix "$WINE_PREFIX" --exe "$GAME_EXE" \
    || die "Failed to register the game in Lutris."
success "Game registered. Reopen Lutris if it was already running."

step "Saving install state"
mkdir -p "${STATE_DIR}/lib"
# Install an independent launcher so the URI handler survives moving this repo.
cp "${SCRIPT_DIR}/launch.sh" "${STATE_DIR}/launch.sh"
cp "${SCRIPT_DIR}/lib/common.sh" "${SCRIPT_DIR}/lib/lutris_bridge.py" \
    "${SCRIPT_DIR}/lib/callback.py" "${STATE_DIR}/lib/"
{
    echo '# Generated by install.sh'
    printf 'LAUNCHER=%q\n' lutris
    printf 'PROTON_VERSION=%q\n' "$PROTON_VERSION"
    printf 'PROTON_ROOT=%q\n' "$PROTON_ROOT"
    printf 'PREFIX_PARENT=%q\n' "$PREFIX_PARENT"
} > "$STATE_FILE"
success "State saved: ${STATE_FILE}"

"${SCRIPT_DIR}/register-handler.sh"

echo ""
success "PTCGL installed successfully!"
info "Launch: ./launch.sh (or open Lutris and click Play)"
info "Direct launch using Lutris's UMU runtime: ./launch.sh --direct"
info "Complete login in the browser and allow the tpcitcgapp:// callback."
