#!/usr/bin/env bash
# Registers the tpcitcgapp:// URI handler so browser OAuth callbacks work.
# Can be re-run independently if the handler breaks.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/lib/common.sh"

load_state

# ── Write the handler script ───────────────────────────────────────────────────
step "Writing URI handler script to ${HANDLER_BIN}"
mkdir -p "$(dirname "$HANDLER_BIN")"

# Refresh the installed launcher when re-registering the handler.
mkdir -p "${STATE_DIR}/lib"
if [[ "$SCRIPT_DIR" != "$STATE_DIR" ]]; then
    cp "${SCRIPT_DIR}/launch.sh" "${STATE_DIR}/launch.sh"
    cp "${SCRIPT_DIR}/lib/common.sh" "${SCRIPT_DIR}/lib/lutris_bridge.py" \
        "${SCRIPT_DIR}/lib/callback.py" "${STATE_DIR}/lib/"
fi
{
    echo '#!/usr/bin/env bash'
    echo '# Generated by register-handler.sh; forwards the URL as one argument.'
    echo 'set -euo pipefail'
    echo '[[ $# -eq 1 && "$1" == tpcitcgapp://* ]] || { echo "Invalid PTCGL callback" >&2; exit 1; }'
    printf 'exec %q "$1"\n' "${STATE_DIR}/launch.sh"
} > "$HANDLER_BIN"

chmod +x "$HANDLER_BIN"
success "Handler script written"

# ── Write the .desktop file ────────────────────────────────────────────────────
step "Writing ${HANDLER_DESKTOP}"
mkdir -p "$(dirname "$HANDLER_DESKTOP")"

desktop_exec="$HANDLER_BIN"
desktop_exec="${desktop_exec//\\/\\\\}"
desktop_exec="${desktop_exec//\"/\\\"}"
desktop_exec="${desktop_exec//\`/\\\`}"
desktop_exec="${desktop_exec//\$/\\\$}"
desktop_exec="${desktop_exec//%/%%}"
# Escape backslashes again for the Desktop Entry string value parser.
desktop_exec="${desktop_exec//\\/\\\\}"
cat > "$HANDLER_DESKTOP" <<DESKTOP_FILE
[Desktop Entry]
Name=PTCGL URI Handler
Comment=Handles tpcitcgapp:// auth callbacks for Pokemon TCG Live
Exec="${desktop_exec}" %u
Type=Application
Terminal=false
NoDisplay=true
MimeType=x-scheme-handler/tpcitcgapp;
DESKTOP_FILE

# ── Register with xdg ─────────────────────────────────────────────────────────
step "Registering tpcitcgapp:// with xdg-mime"

if command -v update-desktop-database &>/dev/null; then
    update-desktop-database "${HOME}/.local/share/applications"
fi

xdg-mime default ptcgl-handler.desktop x-scheme-handler/tpcitcgapp \
    || die "xdg-mime registration failed. Is xdg-utils installed?"

success "URI handler registered"

# Verify
registered=$(xdg-mime query default x-scheme-handler/tpcitcgapp 2>/dev/null || true)
if [[ "$registered" == "ptcgl-handler.desktop" ]]; then
    success "Verified: tpcitcgapp:// → ptcgl-handler.desktop"
else
    warn "xdg-mime verification returned '${registered}' (expected 'ptcgl-handler.desktop')"
    warn "Login may require manual URL copy-paste (see README)."
fi
